# Site settings
title: fips 
subtitle: build system
email: floooh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    cmake-based high-level build system for multi-platform C/C++ projects
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: flohofwoe
github_username:  floooh

# Build settings
markdown: redcarpet 
